"""Remoção coluna user

Revision ID: 329a25819ed2
Revises: 87fa91243bdd
Create Date: 2023-12-22 21:12:22.332675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329a25819ed2'
down_revision: Union[str, None] = '87fa91243bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_id'), ['id'], unique=False)

    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('lancamento', sa.Integer(), nullable=True),
    sa.Column('qtdtemp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], name='fk_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serie_id'), ['id'], unique=False)

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_Usuario_id')

    op.drop_table('Usuario')
    with op.batch_alter_table('Serie', schema=None) as batch_op:
        batch_op.drop_index('ix_Serie_id')

    op.drop_table('Serie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Serie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=True),
    sa.Column('genero', sa.VARCHAR(), nullable=True),
    sa.Column('lancamento', sa.INTEGER(), nullable=True),
    sa.Column('qtdtemp', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Serie', schema=None) as batch_op:
        batch_op.create_index('ix_Serie_id', ['id'], unique=False)

    op.create_table('Usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.create_index('ix_Usuario_id', ['id'], unique=False)

    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serie_id'))

    op.drop_table('serie')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_id'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
