"""Remoção coluna user

Revision ID: 87fa91243bdd
Revises: 
Create Date: 2023-12-22 20:42:43.061433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fa91243bdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Usuario_id'), ['id'], unique=False)

    op.create_table('Serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('lancamento', sa.Integer(), nullable=True),
    sa.Column('qtdtemp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Usuario.id'], name='fk_Usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Serie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Serie_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Serie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Serie_id'))

    op.drop_table('Serie')
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Usuario_id'))

    op.drop_table('Usuario')
    # ### end Alembic commands ###
